# Change these first
owner: dpkg-i-foo-deb # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: Site Principal
    url: https://vc-soft.com
    delay: 1800000  # 30 minutos
  - name: Portal de Autenticación
    url: $KEYCLOAK
  - name: VPN Soporte
    url: $VPN_SOPORTE
  - name: VPN Sodimac
    url: $VPN_SODIMAC
  - name: VPN Davivienda
    url: $VPN_DAVIVIENDA
  - name: AWX
    url: $AWX
  - name: Mail
    url: $VCSOFT_MAIL
  - name: Training
    url: https://training.vc-soft.com
  - name: CRM
    url: $VCSOFT_CRM
  - name: Invoice Colombia
    url: $INVOICE_COLOMBIA
  - name: Invoice Chile
    url: $INVOICE_CHILE
  - name: Invoice Argentina
    url: $INVOICE_ARGENTINA
  - name: Portal TBK Clientes
    url: $PORTAL_TBK_CLIENTES
  - name: Portal TBK Clientes Sandbox
    url: $PORTAL_TBK_CLIENTES_SANDBOX
  - name: Portal TBK Partners
    url: $PORTAL_TBK_PARTNERS
  - name: Portal TBK Partners Sandbox
    url: $PORTAL_TBK_PARTNERS_SANDBOX

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vc-soft.com
  theme: light
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://raw.githubusercontent.com/dpkg-i-foo-deb/upptime/master/assets/vcsoft-small.svg
  name: Monitoreo de servicios
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introTitle: Dashboard de monitoreo **VCSOFT**
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  introMessage: Monitoreo y análisis de servicios, a través del cual se brinda una visión completa y en tiempo real de los servicios críticos ayudando a identificar y resolver problemas de manera proactiva antes de que impacten a los usuarios
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  incidentReport: "Reporte del incidente #$NUMBER →"
  activeIncidentSummary: Inició el $DATE con $POSTS comentarios
  incidentTitle: Detalles del incidente $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Solucionado
  incidentOngoing: Activo
  incidentOpenedAt: Abierto el
  incidentClosedAt: Cerrado el
  incidentViewOnGitHub: Ver y suscribirse en GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Volver a todos los incidentes
  pastIncidents: Incidentes anteriores
  pastIncidentsResolved: Solucionado en $MINUTES minutos con $POSTS comentarios
  liveStatus: Estado en vivo
  overallUptime: "Disponibilidad general: $UPTIME"
  overallUptimeTitle: Disponibilidad general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Tiempo de respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta en los últimos 7 días
  responseTimeMs: Tiempo de respuesta (ms)
  up: Activo
  down: Inactivo
  degraded: Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: Este sitio es de [código abierto]($REPO), utilizando [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Límite de peticiones excedido
  rateLimitExceededIntro: Has excedido el número de peticiones que puedes realizar en una hora, tendrás que esperar una hora para acceder nuevamente. Alternativamente, puedes utilizar un token de acceso de GitHub para acceder.
  rateLimitExceededWhatDoesErrorMean: ¿Qué significa este error?
  rateLimitExceededErrorMeaning: Este sitio utiliza la API de GitHub para acceder a los datos en tiempo real de nuestros sitios. Por defecto, GitHub permite 60 peticiones por hora, las cuales has excedido.
  rateLimitExceededErrorHowCanFix: ¿Cómo lo puedo solucionar?
  rateLimitExceededErrorFix: Puedes esperar una hora y el límite de peticiones de tu dirección IP será restaurado. Alternativamente, puedes utilizar un token de acceso de GitHub y realizar 5000 peticiones en una hora.
  rateLimitExceededGeneratePAT: Aprende cómo generar un token de acceso
  rateLimitExceededHasSet: Hasta establecido un token de acceso.
  rateLimitExceededRemoveToken: Eliminar token
  rateLimitExceededGitHubPAT: Token de acceso de GitHub
  rateLimitExceededCopyPastePAT: Copiar y pegar token
  rateLimitExceededSaveToken: Guardar token
  errorTitle: Ocurrió un error
  errorIntro: Ocurrió un error tratando de obtener las estadísticas.
  errorText: Puedes intentar de nuevo en unos momentos.
  errorHome: Ir al inicio
  pastScheduledMaintenance: Mantenimientos programados con anterioridad
  scheduledMaintenance: Mantenimiento programado
  scheduledMaintenanceSummaryStarted: Inició el $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia $DATE durante $DURATION minutos
  startedAt: Inició el
  startsAt: Finalizó el
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: todo

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
